package com.guyunxinchuan.heritage.music

object ShopCategoryIds {
    const val ALL = "all"
    const val HERITAGE = "heritage"
    const val INSTRUMENT = "instrument"
    const val AROMA = "aroma"
    const val COLLAB = "collab"
    const val SALE = "sale"
}

data class ShopCategoryTab(val id: String, val label: String)

object ShopCatalog {

    private val WC_COVER_IDS = intArrayOf(
        R.drawable.wc_cover_01, R.drawable.wc_cover_02, R.drawable.wc_cover_03, R.drawable.wc_cover_04,
        R.drawable.wc_cover_05, R.drawable.wc_cover_06, R.drawable.wc_cover_07, R.drawable.wc_cover_08,
        R.drawable.wc_cover_09, R.drawable.wc_cover_10, R.drawable.wc_cover_11, R.drawable.wc_cover_12,
        R.drawable.wc_cover_13, R.drawable.wc_cover_14, R.drawable.wc_cover_15, R.drawable.wc_cover_16,
        R.drawable.wc_cover_17, R.drawable.wc_cover_18, R.drawable.wc_cover_19, R.drawable.wc_cover_20,
    )

    private val WC_MOCK_IDS = intArrayOf(
        R.drawable.wc_mock_01, R.drawable.wc_mock_02, R.drawable.wc_mock_03, R.drawable.wc_mock_04,
        R.drawable.wc_mock_05, R.drawable.wc_mock_06, R.drawable.wc_mock_07, R.drawable.wc_mock_08,
        R.drawable.wc_mock_09, R.drawable.wc_mock_10, R.drawable.wc_mock_11, R.drawable.wc_mock_12,
        R.drawable.wc_mock_13, R.drawable.wc_mock_14, R.drawable.wc_mock_15, R.drawable.wc_mock_16,
        R.drawable.wc_mock_17,
    )

    private fun wcCover(i: Int): Int = WC_COVER_IDS[i % WC_COVER_IDS.size]

    private fun wcMock(i: Int): Int = WC_MOCK_IDS[i % WC_MOCK_IDS.size]

    val categoryTabs: List<ShopCategoryTab> = listOf(
        ShopCategoryTab(ShopCategoryIds.ALL, "全部商品"),
        ShopCategoryTab(ShopCategoryIds.HERITAGE, "非遗文创"),
        ShopCategoryTab(ShopCategoryIds.INSTRUMENT, "乐器周边"),
        ShopCategoryTab(ShopCategoryIds.AROMA, "香薰雅物"),
        ShopCategoryTab(ShopCategoryIds.COLLAB, "限定联名"),
        ShopCategoryTab(ShopCategoryIds.SALE, "限时折扣"),
    )

    /** 商城全部商品（含分类、销量、原价等） */
    val allProducts: List<Product> = listOf(
        Product(
            id = "s1",
            name = "敦煌乐器冰箱贴",
            price = 30.0,
            rating = 4.9f,
            description = "敦煌壁画灵感金属冰箱贴，非遗文创伴手礼。",
            imageUrl = "",
            category = "文创",
            tags = listOf("敦煌", "冰箱贴"),
            imageResId = wcCover(0),
            detailHeroResId = wcMock(0),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = 38.0,
            salesCount = 1280,
            isNew = true,
        ),
        Product(
            id = "s2",
            name = "非遗剪纸书签",
            price = 25.0,
            rating = 4.7f,
            description = "手工剪纸书签，传统纹样镂空设计。",
            imageUrl = "",
            category = "文创",
            tags = listOf("剪纸", "书签"),
            imageResId = wcCover(1),
            detailHeroResId = wcMock(1),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = 32.0,
            salesCount = 856,
            isNew = false,
        ),
        Product(
            id = "s3",
            name = "青花瓷香薰蜡烛",
            price = 68.0,
            rating = 4.8f,
            description = "青花瓷纹陶瓷杯身，天然植物蜡。",
            imageUrl = "",
            category = "香薰",
            tags = listOf("青花", "蜡烛"),
            imageResId = wcCover(2),
            detailHeroResId = wcMock(2),
            shopCategoryId = ShopCategoryIds.AROMA,
            originalPrice = 88.0,
            salesCount = 642,
            isNew = true,
        ),
        Product(
            id = "s4",
            name = "蜀绣丝巾",
            price = 128.0,
            rating = 4.9f,
            description = "手工蜀绣方巾，桑蚕丝底料。",
            imageUrl = "",
            category = "服饰",
            tags = listOf("蜀绣", "丝巾"),
            imageResId = wcCover(3),
            detailHeroResId = wcMock(3),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = 168.0,
            salesCount = 420,
            isNew = false,
        ),
        Product(
            id = "s5",
            name = "景泰蓝手镯",
            price = 89.0,
            rating = 4.6f,
            description = "铜胎掐丝珐琅工艺，国风配色。",
            imageUrl = "",
            category = "首饰",
            tags = listOf("景泰蓝"),
            imageResId = wcCover(4),
            detailHeroResId = wcMock(4),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = null,
            salesCount = 310,
            isNew = false,
        ),
        Product(
            id = "s6",
            name = "古琴拨片礼盒",
            price = 48.0,
            rating = 4.8f,
            description = "牛角材质拨片，配锦盒与养护说明。",
            imageUrl = "",
            category = "乐器",
            tags = listOf("古琴", "拨片"),
            imageResId = wcCover(5),
            detailHeroResId = wcMock(5),
            shopCategoryId = ShopCategoryIds.INSTRUMENT,
            originalPrice = 58.0,
            salesCount = 512,
            isNew = true,
        ),
        Product(
            id = "s7",
            name = "非遗大师联名乐谱",
            price = 118.0,
            rating = 4.9f,
            description = "大师校订古谱影印，附导读册。",
            imageUrl = "",
            category = "乐谱",
            tags = listOf("联名", "乐谱"),
            imageResId = wcCover(6),
            detailHeroResId = wcMock(6),
            shopCategoryId = ShopCategoryIds.COLLAB,
            originalPrice = 158.0,
            salesCount = 289,
            isNew = true,
        ),
        Product(
            id = "s8",
            name = "线香礼盒套装",
            price = 96.0,
            rating = 4.7f,
            description = "天然沉香线香，竹制香插与礼盒。",
            imageUrl = "",
            category = "香道",
            tags = listOf("线香", "礼盒"),
            imageResId = wcCover(7),
            detailHeroResId = wcMock(7),
            shopCategoryId = ShopCategoryIds.AROMA,
            originalPrice = 128.0,
            salesCount = 730,
            isNew = false,
        ),
        Product(
            id = "s9",
            name = "铜制小号香炉",
            price = 158.0,
            rating = 4.8f,
            description = "仿古三足炉形，适合盘香与塔香。",
            imageUrl = "",
            category = "香道",
            tags = listOf("香炉"),
            imageResId = wcCover(8),
            detailHeroResId = wcMock(8),
            shopCategoryId = ShopCategoryIds.AROMA,
            originalPrice = 198.0,
            salesCount = 205,
            isNew = false,
        ),
        Product(
            id = "s10",
            name = "敦煌联名帆布袋",
            price = 59.0,
            rating = 4.6f,
            description = "加厚帆布，飞天纹样数码印花。",
            imageUrl = "",
            category = "包袋",
            tags = listOf("敦煌", "联名"),
            imageResId = wcCover(9),
            detailHeroResId = wcMock(9),
            shopCategoryId = ShopCategoryIds.COLLAB,
            originalPrice = 79.0,
            salesCount = 940,
            isNew = false,
        ),
        Product(
            id = "s11",
            name = "苏绣团扇（限时）",
            price = 168.0,
            rating = 4.9f,
            description = "双面绣团扇，檀木扇柄。",
            imageUrl = "",
            category = "工艺",
            tags = listOf("苏绣", "团扇"),
            imageResId = wcCover(10),
            detailHeroResId = wcMock(10),
            shopCategoryId = ShopCategoryIds.SALE,
            originalPrice = 228.0,
            salesCount = 156,
            isNew = false,
        ),
        Product(
            id = "s12",
            name = "古琴模型摆件",
            price = 198.0,
            rating = 4.7f,
            description = "1:8 缩比仲尼式古琴，鸡翅木底座。",
            imageUrl = "",
            category = "摆件",
            tags = listOf("古琴", "模型"),
            imageResId = wcCover(11),
            detailHeroResId = wcMock(11),
            shopCategoryId = ShopCategoryIds.INSTRUMENT,
            originalPrice = 248.0,
            salesCount = 178,
            isNew = true,
        ),
        Product(
            id = "s13",
            name = "竹笛挂饰（迷你）",
            price = 36.0,
            rating = 4.5f,
            description = "手工竹制迷你笛，可作包挂与车挂。",
            imageUrl = "",
            category = "挂饰",
            tags = listOf("竹笛"),
            imageResId = wcCover(12),
            detailHeroResId = wcMock(12),
            shopCategoryId = ShopCategoryIds.INSTRUMENT,
            originalPrice = null,
            salesCount = 402,
            isNew = false,
        ),
        Product(
            id = "s14",
            name = "大师签名折扇",
            price = 268.0,
            rating = 5.0f,
            description = "宣纸折扇，非遗书法大师题字限量版。",
            imageUrl = "",
            category = "联名",
            tags = listOf("折扇", "限量"),
            imageResId = wcCover(13),
            detailHeroResId = wcMock(13),
            shopCategoryId = ShopCategoryIds.COLLAB,
            originalPrice = 328.0,
            salesCount = 92,
            isNew = true,
        ),
        Product(
            id = "s15",
            name = "香薰精油补充装",
            price = 45.0,
            rating = 4.6f,
            description = "与店内香薰蜡烛同系列香型。",
            imageUrl = "",
            category = "香薰",
            tags = listOf("精油"),
            imageResId = wcCover(14),
            detailHeroResId = wcMock(14),
            shopCategoryId = ShopCategoryIds.AROMA,
            originalPrice = 58.0,
            salesCount = 560,
            isNew = false,
        ),
        Product(
            id = "s16",
            name = "云纹金属书签（套装）",
            price = 42.0,
            rating = 4.8f,
            description = "激光镂空云雷纹，黄铜镀哑光。",
            imageUrl = "",
            category = "文创",
            tags = listOf("书签", "金属"),
            imageResId = wcCover(15),
            detailHeroResId = wcMock(15),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = 52.0,
            salesCount = 670,
            isNew = false,
        ),
        Product(
            id = "s17",
            name = "非遗皮影小夜灯",
            price = 128.0,
            rating = 4.7f,
            description = "皮影元素亚克力灯罩，可调光。",
            imageUrl = "",
            category = "家居",
            tags = listOf("皮影", "夜灯"),
            imageResId = wcCover(16),
            detailHeroResId = wcMock(16),
            shopCategoryId = ShopCategoryIds.HERITAGE,
            originalPrice = 168.0,
            salesCount = 240,
            isNew = true,
        ),
        Product(
            id = "s18",
            name = "联名款蓝牙音箱（宫调）",
            price = 399.0,
            rating = 4.8f,
            description = "宫灯造型腔体，与民乐厂牌联名调音。",
            imageUrl = "",
            category = "数码",
            tags = listOf("联名", "音箱"),
            imageResId = wcCover(17),
            detailHeroResId = wcMock(17),
            shopCategoryId = ShopCategoryIds.COLLAB,
            originalPrice = 499.0,
            salesCount = 133,
            isNew = true,
        ),
        Product(
            id = "s19",
            name = "手工漆器首饰盒（清仓）",
            price = 188.0,
            rating = 4.7f,
            description = "大漆莳绘小盒，微瑕特价出清。",
            imageUrl = "",
            category = "工艺",
            tags = listOf("漆器", "清仓"),
            imageResId = wcCover(18),
            detailHeroResId = wcMock(18),
            shopCategoryId = ShopCategoryIds.SALE,
            originalPrice = 320.0,
            salesCount = 45,
            isNew = false,
        ),
    )

    /** 与 `wc_cover_*` 顺序对齐的列表下标（找不到时 0）。 */
    fun catalogIndex(product: Product): Int =
        allProducts.indexOfFirst { it.id == product.id }.takeIf { it >= 0 } ?: 0

    fun filterByCategory(products: List<Product>, categoryId: String): List<Product> {
        if (categoryId == ShopCategoryIds.ALL) return products
        return products.filter { it.shopCategoryId == categoryId }
    }
}
