/**
 * AUTO-GENERATED by `tools/sync_stories_data.py` from `data/故事/*.txt`.
 * 主包仅含列表字段（无正文）。完整正文见 `pkg/data/storyBodies.ts`。
 */
import { assetUrl } from "../utils/assetUrl";

export interface Story {
  id: string;
  title: string;
  author: string;
  category: string;
  excerpt: string;
  body: string;
  publishTime: string;
  likeCount: number;
  commentCount: number;
  readCount: number;
  tags: string[];
  isLiked?: boolean;
  isSaved?: boolean;
  coverSrc: string;
  coverWidth: number;
  coverHeight: number;
}

export type StoryCard = Omit<Story, "body">;

export const STORY_CATEGORIES = ["推荐", "戏曲", "曲艺", "古琴", "古乐器", "民间舞蹈"] as const;

export const STORIES: StoryCard[] = [
  {
    id: "story_henan_zhuizi",
    title: `弦韵传薪 坠音润豫——国家级非遗河南坠子与传承人陈胜利`, 
    author: `陈胜利 · 第五批国家级非遗河南坠子代表性传承人`, 
    category: "曲艺", 
    excerpt: `弦音婉转诉古今，坠韵悠长润中原。河南坠子，这门扎根中原大地的国家级非物质文化遗产，是中国曲艺宝库中极具地域特色的瑰宝，以质朴的唱腔、灵动的旋律，承载着河南人民的喜怒哀乐与乡土情怀，历经百年流转，在弦歌不辍中传递着中原文脉。而第五批国家级非遗河南坠子代表性传承人陈胜利，便以一生坚守，成为这门古老曲艺的当代领军者，用匠心守护坠子古韵，用行动续写传承新篇。`, 
    publishTime: "2024-04-22", 
    likeCount: 1267, 
    commentCount: 92, 
    readCount: 8540, 
    tags: ["河南坠子", "曲艺", "坠胡", "中原非遗"], 
    coverSrc: assetUrl("/images/story/henan_zhuizi.jpg"),
    coverWidth: 1024,
    coverHeight: 1536,
  },
  {
    id: "story_guqin",
    title: `一弦古琴承浙韵，妙手传薪润新声——当代浙派古琴家王光磊的琴路春秋`, 
    author: `王光磊 · 浙派徐门第四代嫡传`, 
    category: "古琴", 
    excerpt: `古琴，承载着中华千年文脉的传统乐器，以其清越悠远的音色、淡泊宁静的气韵，成为东方美学的精神符号。当代浙派古琴家王光磊，便以一床古琴为伴，承浙派徐门之精髓，兼收诸家之所长，在演奏、教育与推广的道路上，让这门古老乐器走出深巷，焕发新生。`, 
    publishTime: "2024-04-19", 
    likeCount: 1132, 
    commentCount: 76, 
    readCount: 7320, 
    tags: ["古琴", "浙派", "雁山堂", "传统音乐"], 
    coverSrc: assetUrl("/images/story/guqin.jpg"),
    coverWidth: 1024,
    coverHeight: 1536,
  },
  {
    id: "story_siping_diao",
    title: `韵润中州 戏续薪火——河南国家级非遗四平调与传承人付梅的坚守`, 
    author: `付梅 · 国家级非遗四平调代表性传承人`, 
    category: "戏曲", 
    excerpt: `一腔乡音传古韵，半生坚守续戏魂。四平调，这门扎根豫鲁苏皖交界地带、流淌着中原民俗血脉的国家级非物质文化遗产，作为独具特色的传统戏剧形式，以其四平八稳的唱腔、通俗易懂的唱词、鲜活生动的演绎，在岁月长河中滋养着一方百姓，而国家级非遗四平调传承人付梅，以一生赴戏约，用坚守与担当，让这门古老剧种在新时代焕发勃勃生机。`, 
    publishTime: "2024-04-15", 
    likeCount: 998, 
    commentCount: 64, 
    readCount: 6850, 
    tags: ["四平调", "戏曲", "商丘", "中原非遗"], 
    coverSrc: assetUrl("/images/story/siping_diao.jpg"),
    coverWidth: 1024,
    coverHeight: 1536,
  },
  {
    id: "story_heluo_dagu",
    title: `鼓板传古韵 乡音润河洛——国家级非遗河洛大鼓的百年传承`, 
    author: `河洛文化研究 · 编辑部`, 
    category: "曲艺", 
    excerpt: `一鼓一板唱古今，一腔乡音润人心。河洛大鼓，这门扎根河南洛阳、响彻河洛大地的国家级非物质文化遗产，作为流传百年的民间说唱艺术，是流淌在河洛乡土间的音律血脉，更是老一辈洛阳人刻在记忆里的市井烟火，它以质朴的唱腔、鲜活的内容，承载着河洛地区的文化根脉，成为河南民间音乐中极具特色的说唱瑰宝。`, 
    publishTime: "2024-04-10", 
    likeCount: 824, 
    commentCount: 51, 
    readCount: 5620, 
    tags: ["河洛大鼓", "说唱", "洛阳", "中原非遗"], 
    coverSrc: assetUrl("/images/story/heluo_dagu.jpg"),
    coverWidth: 1024,
    coverHeight: 1536,
  },
  {
    id: "story_jiulian_deng",
    title: `莲灯映古俗 非遗续华章——九莲灯的千年传承故事`, 
    author: `民俗影像志 · 田野记述`, 
    category: "民间舞蹈", 
    excerpt: `一盏莲灯承古韵，万点星火续文脉。九莲灯，作为流传于中华大地的传统民间舞蹈类非遗项目，扎根多地民俗土壤，承载着古人的祈福祈愿，历经数百年迭代，在锣鼓声中、灯影流转间，将民间智慧与文化底蕴代代相传，成为镌刻在民俗里的非遗印记。它并非单一形态，而是在不同地域演化出独特风貌，却始终以“灯”为魂、以“舞”为骨，诉说着跨越时空的民俗情怀。`, 
    publishTime: "2024-04-05", 
    likeCount: 712, 
    commentCount: 43, 
    readCount: 4980, 
    tags: ["九莲灯", "民间舞蹈", "元宵", "上党八音"], 
    coverSrc: assetUrl("/images/story/jiulian_deng.jpg"),
    coverWidth: 1024,
    coverHeight: 1536,
  },
  {
    id: "story_puyang_daxianxi",
    title: `一管锡笛，守住千年曲韵 —— 非遗传承人戴建平的乐器坚守故事`, 
    author: `戴建平 · 国家级非遗大弦戏代表性传承人`, 
    category: "戏曲", 
    excerpt: `1948 年，戴建平生于河南濮阳这片浸润着戏曲古韵的土地。自年少时，一支古朴的锡笛便走进了他的生命，从此与大弦戏结下一生不解之缘。作为国家级非遗大弦戏代表性传承人、大弦戏古曲牌与锡笛第七代传人，他一生以锡笛为魂，以古曲为脉，用一管乐器守住了跨越唐宋的戏曲声腔文脉。`, 
    publishTime: "2024-04-02", 
    likeCount: 658, 
    commentCount: 37, 
    readCount: 4420, 
    tags: ["大弦戏", "锡笛", "唐宋古曲", "中原非遗"], 
    coverSrc: assetUrl("/images/story/puyang_daxianxi.jpg"),
    coverWidth: 1536,
    coverHeight: 1024,
  },
  {
    id: "story_konghou_yishu",
    title: `弦鸣千载 雅韵新生——河南非遗箜篌艺术的传承与绽放`, 
    author: `鲁璐 · 河南省非遗箜篌艺术代表性传承人`, 
    category: "古乐器", 
    excerpt: `一弦一柱含古韵，一弹一奏越千年。箜篌，这门镌刻着中华文脉的河南省非物质文化遗产，作为中国传统七弦拨弦乐器，历经秦汉肇始、隋唐鼎盛、明清沉寂的千年流转，在岁月长河中沉淀出独特的艺术魅力，如今在传承人的坚守与创新中，重焕新生，奏响跨越时空的中原雅音。`, 
    publishTime: "2024-03-28", 
    likeCount: 1184, 
    commentCount: 88, 
    readCount: 7860, 
    tags: ["箜篌", "古乐器", "雅乐", "久鼎空侯博物馆"], 
    coverSrc: assetUrl("/images/story/konghou_yishu.jpg"),
    coverWidth: 1254,
    coverHeight: 1254,
  },
];

export function storyById(id: string): StoryCard | undefined {
  return STORIES.find((s) => s.id === id);
}
